# Generated by Django 5.1.6 on 2025-02-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=50)),
                ('chapter', models.CharField(max_length=50)),
            ],
        ),
    ]
