# Dictionary containing all chapters and their topics
chapters_and_topics = {
    "7.1": [
        "Data types, data structures and abstract data types", 
        "Time and space analysis of algorithms (Big oh, omega and theta notations)", 
        "Linear data structure (Stack and queue implementation)", 
        "Stack application: infix to postfix conversion, and evaluation of postfix expression", 
        "Array implementation of lists", 
        "Stack and Queues as list", 
        "Static list structure", 
        "Static and dynamic list structure", 
        "Dynamic implementation of linked list", 
        "Types of Linked list: Singly Linked list, Doubly Linked list, and Circular Linked list", 
        "Basic operations on Linked list: creation of linked list, insertion of node in different positions, and deletion of nodes from different positions", 
        "Doubly linked lists and its applications", 
        "Concept of Tree", 
        "Operation in Binary tree", 
        "Tree search", 
        "Insertion/deletions in Binary Tree", 
        "Tree traversals (pre-order, post-order and in-order)", 
        "Height, level and depth of a tree", 
        "AVL balanced trees"
    ],
    "7.2": [
        "Types of sorting: internal and external", 
        "Insertion and selection sort", 
        "Exchange sort", 
        "Merge and Radix sort", 
        "Shell sort", 
        "Heap sort as a priority queue", 
        "Big ‘O’ notation and Efficiency of sorting", 
        "Search technique", 
        "Sequential search", 
        "Binary search", 
        "Tree search", 
        "General search tree", 
        "Hashing: Hash function and hash tables", 
        "Collision resolution technique", 
        "Undirected and Directed Graphs", 
        "Representation of Graph", 
        "Transitive closure of graph", 
        "Warshall’s algorithm", 
        "Depth First Traversal and Breadth First Traversal of Graph", 
        "Topological sorting (Depth first, Breadth first topological sorting)", 
        "Minimum spanning trees (Prim’s, Kruskal’s and Round-Robin algorithms)", 
        "Shortest-path algorithm (Greedy algorithm, and Dijkstra’s Algorithm)"
    ],
    "7.3": [
        "Data Abstraction and Data Independence", 
        "Schema and Instances", 
        "E-R Model", 
        "Strong and Weak Entity Sets", 
        "Attributes and Keys", 
        "E-R Diagram", 
        "Different Normal Forms (1st, 2nd, 3rd, BCNF)", 
        "Functional Dependencies", 
        "Integrity Constraints and Domain Constraints", 
        "Relations (Joined, Derived)", 
        "Queries under DDL and DML Commands", 
        "Views", 
        "Assertions and Triggering", 
        "Relational Algebra", 
        "Query Cost Estimation", 
        "Query Operations", 
        "Evaluation of Expressions", 
        "Query Optimization", 
        "Query Decomposition"
    ],
    "7.4": [
        "ACID properties", 
        "Concurrent Executions", 
        "Serializability Concept", 
        "Lock based Protocols", 
        "Deadlock handling and Prevention", 
        "Failure Classification", 
        "Recovery and Atomicity", 
        "Log-based Recovery"
    ],
    "7.5": [
        "Evolution of Operating System", 
        "Type of Operating System", 
        "Operating System Components", 
        "Operating System Structure", 
        "Operating System Services", 
        "Introduction to Process", 
        "Process description", 
        "Process states", 
        "Process control", 
        "Threads", 
        "Processes and Threads", 
        "Types of scheduling", 
        "Principles of Concurrency", 
        "Critical Region", 
        "Race Condition", 
        "Mutual Exclusion", 
        "Semaphores and Mutex", 
        "Message Passing", 
        "Monitors", 
        "Classical Problems of Synchronization"
    ],
    "7.6": [
        "Memory address", 
        "Swapping and Managing Free Memory Space", 
        "Virtual Memory Management", 
        "Demand Paging", 
        "Performance", 
        "Page Replacement Algorithms", 
        "Introduction to File, Directory and File Paths", 
        "File System Implementation", 
        "Impact of Allocation Policy on Fragmentation", 
        "Mapping File Blocks on The Disk Platter", 
        "File System Performance", 
        "Administration Tasks", 
        "User Account Management", 
        "Start and Shutdown Procedures"
    ]
}